# Generated by Django 5.0.3 on 2024-04-17 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField(default=0)),
                ('subgrupo', models.IntegerField(default=0)),
                ('seccion', models.IntegerField(default=0)),
                ('articulo', models.TextField()),
                ('serial', models.CharField(max_length=200, verbose_name='Serial')),
                ('unidad_medida', models.CharField(max_length=100, verbose_name='Unidad de Medida')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(max_length=200)),
                ('fecha_salida', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('serial', models.CharField(max_length=200, verbose_name='Serial')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serving.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUnidad', models.CharField(max_length=200, verbose_name='Nombre de la Unidad')),
                ('comandante', models.CharField(max_length=200, verbose_name='Comandante')),
                ('ubicacion', models.TextField(null=True)),
                ('telefono', models.CharField(max_length=200, verbose_name='telefono')),
                ('articulos', models.ManyToManyField(through='serving.ArticuloUnidad', to='serving.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulounidad',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serving.unidad'),
        ),
    ]
