# Generated by Django 5.0.4 on 2024-04-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serving', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulomodel',
            old_name='codigoEquipo',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='articulomodel',
            name='estadoActual',
        ),
    ]
