# Generated by Django 5.0.4 on 2024-04-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serving', '0002_rename_codigoequipo_articulomodel_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulomodel',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
